#' @title Creates global site by latitudinal-longitudinal grid cell
#' dispersion field abundance counts.
#'
#' @description Create global abundance counts matrix by merging the dispersion
#' fields from the list of dispersion field maps generated by
#' \code{dsp_create_from_survey} or \code{dsp_create_from_gdb} function.
#'
#' @param dispersion.field Dispersion field list generated by
#'                        \code{dsp_create_from_survey} or
#'                        \code{dsp_create_from_gdb} function.
#'
#' @return The global site by grid cell abundance counts matrix.
#' @keywords dispersion field, global abundance counts
#'
#' @examples
#'
#' data("dispersion_field_ex")
#' mat <- dsp_to_matrix(dispersion_field_ex)
#'
#'
#' @export

dsp_to_matrix <- function(dispersion.field) {
  cat("\n Converting dispersion fields to matrix rows \n")
  pb <- txtProgressBar()
  temp_data <- dispersion.field[[1]]
  temp_data[is.na(temp_data)] <- 0
  map_data <- matrix(NA, length(dispersion.field), dim(temp_data)[1] * dim(temp_data)[2])
  for (l in 1:length(dispersion.field)) {
    temp_data <- dispersion.field[[l]]
    temp_data[is.na(temp_data)] <- 0
    temp_data_vec <- matrix(as.matrix(temp_data),
      ncol = dim(temp_data)[1] * dim(temp_data)[2], byrow = TRUE)
    map_data[l, ] <- temp_data_vec
    setTxtProgressBar(pb, l / length(dispersion.field))
  }
  rownames(map_data) <- names(dispersion.field)
  return(map_data)
}

